spring.application.name=Backend

# --- KONEKSI DATABASE (Sudah saya rapikan) ---
# URL hanya alamat server
spring.datasource.url=jdbc:postgresql://ep-empty-hall-a1lskv6b-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

# Username & Password dipisah agar Spring Boot membacanya dengan benar
spring.datasource.username=neondb_owner
spring.datasource.password=npg_iRwP4DZYvrO6

# Driver Wajib
spring.datasource.driver-class-name=org.postgresql.Driver

# --- PENTING: AGAR TABEL DIBUAT OTOMATIS ---
# Tanpa baris ini, database kamu kosong (tidak ada tabel scores/players)
spring.jpa.hibernate.ddl-auto=update

# Untuk melihat log SQL di terminal (memudahkan debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect