spring.application.name=Backend2
spring.datasource.url=jdbc:postgresql://ep-odd-fog-a16lit7t-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_3Fks0fOjeSuy&sslmode=require&channelBinding=require

spring.jpa.hibernate.ddl-auto=update